"""init

Revision ID: ad67cf12d09d
Revises: 
Create Date: 2026-09-30 22:39:47.640179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad67cf12d09d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('universities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('domain', sa.String(length=100), nullable=True),
    sa.Column('sso_entity_id', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_universities_active', 'universities', ['is_active'], unique=False)
    op.create_index(op.f('ix_universities_slug'), 'universities', ['slug'], unique=True)
    op.create_table('campus_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('snapshot_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('university_id', sa.UUID(), nullable=True),
    sa.Column('period', sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', name='snapshotperiod'), nullable=False),
    sa.Column('total_check_ins', sa.Integer(), nullable=False),
    sa.Column('unique_students_count', sa.Integer(), nullable=False),
    sa.Column('avg_mood_score', sa.Double(), nullable=True),
    sa.Column('avg_stress_score', sa.Double(), nullable=True),
    sa.Column('stress_distribution', sa.JSON(), nullable=False),
    sa.Column('counseling_request_count', sa.Integer(), nullable=False),
    sa.Column('escalation_count', sa.Integer(), nullable=False),
    sa.Column('top_factors', sa.JSON(), nullable=False),
    sa.Column('resource_engagement_count', sa.Integer(), nullable=False),
    sa.Column('min_group_size_met', sa.Boolean(), nullable=False),
    sa.Column('trends_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_campus_snapshots_date_period', 'campus_snapshots', ['snapshot_date', 'period'], unique=True)
    op.create_index(op.f('ix_campus_snapshots_snapshot_date'), 'campus_snapshots', ['snapshot_date'], unique=False)
    op.create_index('ix_campus_snapshots_university', 'campus_snapshots', ['university_id', 'snapshot_date'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('student_id_hash', sa.String(length=64), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('STUDENT', 'COUNSELOR', 'WELLBEING_ADMIN', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('program', sa.String(length=100), nullable=True),
    sa.Column('year_of_study', sa.Integer(), nullable=True),
    sa.Column('university_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('sso_subject', sa.String(length=255), nullable=True),
    sa.Column('consent_version', sa.String(length=20), nullable=True),
    sa.Column('consent_given_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sso_subject')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index('ix_users_email_active', 'users', ['email', 'is_active'], unique=False)
    op.create_index('ix_users_role_active', 'users', ['role', 'is_active'], unique=False)
    op.create_index(op.f('ix_users_student_id_hash'), 'users', ['student_id_hash'], unique=True)
    op.create_table('appointments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('counselor_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('mode', sa.Enum('ONLINE', 'IN_PERSON', 'EITHER', name='sessionmode'), nullable=False),
    sa.Column('status', sa.Enum('UPCOMING', 'COMPLETED', 'CANCELLED', 'NO_SHOW', name='appointmentstatus'), nullable=False),
    sa.Column('meeting_link', sa.String(length=500), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['counselor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointments_counselor_id'), 'appointments', ['counselor_id'], unique=False)
    op.create_index('ix_appointments_counselor_scheduled', 'appointments', ['counselor_id', 'scheduled_at'], unique=False)
    op.create_index(op.f('ix_appointments_scheduled_at'), 'appointments', ['scheduled_at'], unique=False)
    op.create_index('ix_appointments_status', 'appointments', ['status'], unique=False)
    op.create_index(op.f('ix_appointments_student_id'), 'appointments', ['student_id'], unique=False)
    op.create_index('ix_appointments_student_scheduled', 'appointments', ['student_id', 'scheduled_at'], unique=False)
    op.create_table('assessments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('assessment_type', sa.Enum('PERIODIC', 'INTAKE', name='assessmenttype'), nullable=False),
    sa.Column('responses', sa.JSON(), nullable=False),
    sa.Column('support_level', sa.String(length=30), nullable=False),
    sa.Column('distress_score', sa.Double(), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_assessments_student_completed', 'assessments', ['student_id', 'completed_at'], unique=False)
    op.create_index(op.f('ix_assessments_student_id'), 'assessments', ['student_id'], unique=False)
    op.create_index('ix_assessments_type', 'assessments', ['assessment_type'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('actor_role', sa.String(length=30), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=50), nullable=True),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('user_agent_hash', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_action', 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_logs_actor_timestamp', 'audit_logs', ['actor_id', 'timestamp'], unique=False)
    op.create_index('ix_audit_logs_resource', 'audit_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_table('check_ins',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mood', sa.Enum('VERY_GOOD', 'GOOD', 'OKAY', 'DIFFICULT', 'VERY_DIFFICULT', name='moodlevel'), nullable=False),
    sa.Column('stress', sa.Enum('LOW', 'MODERATE', 'ELEVATED', 'HIGH', name='stresslevel'), nullable=False),
    sa.Column('energy', sa.Enum('LOW', 'MODERATE', 'STABLE', 'HIGH', name='energylevel'), nullable=False),
    sa.Column('sleep', sa.Enum('POOR', 'NEEDS_ATTENTION', 'ADEQUATE', 'GOOD', name='sleepquality'), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('support_level', sa.Enum('SELF_GUIDED', 'ADDITIONAL', 'COUNSELOR', 'URGENT', name='supportlevel'), nullable=False),
    sa.Column('distress_score', sa.Double(), nullable=True),
    sa.Column('escalation_triggered', sa.Boolean(), nullable=False),
    sa.Column('escalation_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_check_ins_escalation', 'check_ins', ['escalation_triggered'], unique=False)
    op.create_index('ix_check_ins_student_completed', 'check_ins', ['student_id', 'completed_at'], unique=False)
    op.create_index(op.f('ix_check_ins_student_id'), 'check_ins', ['student_id'], unique=False)
    op.create_index('ix_check_ins_support_level', 'check_ins', ['support_level'], unique=False)
    op.create_table('consent_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('given_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('analytics_consent', sa.Boolean(), nullable=False),
    sa.Column('research_consent', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consent_records_student_id'), 'consent_records', ['student_id'], unique=False)
    op.create_index('ix_consent_records_student_version', 'consent_records', ['student_id', 'version'], unique=False)
    op.create_table('mood_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('avg_mood_score', sa.Double(), nullable=False),
    sa.Column('avg_stress_score', sa.Double(), nullable=False),
    sa.Column('check_in_count', sa.Integer(), nullable=False),
    sa.Column('sleep_rating', sa.Double(), nullable=True),
    sa.Column('energy_rating', sa.Double(), nullable=True),
    sa.Column('top_tags', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mood_entries_date'), 'mood_entries', ['date'], unique=False)
    op.create_index('ix_mood_entries_student_date', 'mood_entries', ['student_id', 'date'], unique=True)
    op.create_index(op.f('ix_mood_entries_student_id'), 'mood_entries', ['student_id'], unique=False)
    op.create_table('resources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=220), nullable=False),
    sa.Column('category', sa.Enum('STRESS', 'ACADEMIC', 'SLEEP', 'RELATIONSHIPS', 'LONELINESS', 'ANXIETY', 'FOCUS', 'BURNOUT', 'CAMPUS', name='resourcecategory'), nullable=False),
    sa.Column('type', sa.Enum('ARTICLE', 'AUDIO', 'GUIDE', 'CAMPUS', 'EXTERNAL', name='resourcetype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('read_time_seconds', sa.Integer(), nullable=True),
    sa.Column('author', sa.String(length=100), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_resources_category_active', 'resources', ['category', 'is_active'], unique=False)
    op.create_index('ix_resources_published', 'resources', ['published_at'], unique=False)
    op.create_index(op.f('ix_resources_slug'), 'resources', ['slug'], unique=True)
    op.create_table('counseling_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('preferred_mode', sa.Enum('ONLINE', 'IN_PERSON', 'EITHER', name='sessionmode'), nullable=False),
    sa.Column('preferred_times', sa.JSON(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'REVIEWING', 'SCHEDULED', 'COMPLETED', 'CANCELLED', name='counselingrequeststatus'), nullable=False),
    sa.Column('assigned_counselor_id', sa.UUID(), nullable=True),
    sa.Column('appointment_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['assigned_counselor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_counseling_requests_counselor_status', 'counseling_requests', ['assigned_counselor_id', 'status'], unique=False)
    op.create_index(op.f('ix_counseling_requests_student_id'), 'counseling_requests', ['student_id'], unique=False)
    op.create_index('ix_counseling_requests_student_status', 'counseling_requests', ['student_id', 'status'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('type', sa.Enum('EXERCISE', 'TECHNIQUE', 'RESOURCE', 'SOCIAL', 'PROFESSIONAL', name='recommendationtype'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('source', sa.Enum('RULE_BASED', 'LLM', 'HYBRID', name='recommendationsource'), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('dismissed', sa.Boolean(), nullable=False),
    sa.Column('clicked', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ai_assisted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_recommendations_student_active', 'recommendations', ['student_id', 'dismissed', 'expires_at'], unique=False)
    op.create_index('ix_recommendations_student_generated', 'recommendations', ['student_id', 'generated_at'], unique=False)
    op.create_index(op.f('ix_recommendations_student_id'), 'recommendations', ['student_id'], unique=False)
    op.create_table('support_cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_ref', sa.String(length=30), nullable=False),
    sa.Column('check_in_id', sa.UUID(), nullable=True),
    sa.Column('assessment_id', sa.UUID(), nullable=True),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('priority', sa.Enum('STANDARD', 'ELEVATED', 'URGENT', name='casepriority'), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'REVIEWING', 'CONTACTED', 'SCHEDULED', 'RESOLVED', 'CANCELLED', name='casestatus'), nullable=False),
    sa.Column('reason_summary', sa.Text(), nullable=False),
    sa.Column('assigned_counselor_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.JSON(), nullable=False),
    sa.Column('escalation_source', sa.Enum('AUTOMATED', 'MANUAL', 'STUDENT_INITIATED', name='escalationsource'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.ForeignKeyConstraint(['assigned_counselor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['check_in_id'], ['check_ins.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_support_cases_assigned', 'support_cases', ['assigned_counselor_id', 'status'], unique=False)
    op.create_index(op.f('ix_support_cases_case_ref'), 'support_cases', ['case_ref'], unique=True)
    op.create_index('ix_support_cases_status_priority', 'support_cases', ['status', 'priority'], unique=False)
    op.create_index('ix_support_cases_student', 'support_cases', ['student_id'], unique=False)
    op.create_index(op.f('ix_support_cases_student_id'), 'support_cases', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_support_cases_student_id'), table_name='support_cases')
    op.drop_index('ix_support_cases_student', table_name='support_cases')
    op.drop_index('ix_support_cases_status_priority', table_name='support_cases')
    op.drop_index(op.f('ix_support_cases_case_ref'), table_name='support_cases')
    op.drop_index('ix_support_cases_assigned', table_name='support_cases')
    op.drop_table('support_cases')
    op.drop_index(op.f('ix_recommendations_student_id'), table_name='recommendations')
    op.drop_index('ix_recommendations_student_generated', table_name='recommendations')
    op.drop_index('ix_recommendations_student_active', table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index('ix_counseling_requests_student_status', table_name='counseling_requests')
    op.drop_index(op.f('ix_counseling_requests_student_id'), table_name='counseling_requests')
    op.drop_index('ix_counseling_requests_counselor_status', table_name='counseling_requests')
    op.drop_table('counseling_requests')
    op.drop_index(op.f('ix_resources_slug'), table_name='resources')
    op.drop_index('ix_resources_published', table_name='resources')
    op.drop_index('ix_resources_category_active', table_name='resources')
    op.drop_table('resources')
    op.drop_index(op.f('ix_mood_entries_student_id'), table_name='mood_entries')
    op.drop_index('ix_mood_entries_student_date', table_name='mood_entries')
    op.drop_index(op.f('ix_mood_entries_date'), table_name='mood_entries')
    op.drop_table('mood_entries')
    op.drop_index('ix_consent_records_student_version', table_name='consent_records')
    op.drop_index(op.f('ix_consent_records_student_id'), table_name='consent_records')
    op.drop_table('consent_records')
    op.drop_index('ix_check_ins_support_level', table_name='check_ins')
    op.drop_index(op.f('ix_check_ins_student_id'), table_name='check_ins')
    op.drop_index('ix_check_ins_student_completed', table_name='check_ins')
    op.drop_index('ix_check_ins_escalation', table_name='check_ins')
    op.drop_table('check_ins')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_resource', table_name='audit_logs')
    op.drop_index('ix_audit_logs_actor_timestamp', table_name='audit_logs')
    op.drop_index('ix_audit_logs_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_assessments_type', table_name='assessments')
    op.drop_index(op.f('ix_assessments_student_id'), table_name='assessments')
    op.drop_index('ix_assessments_student_completed', table_name='assessments')
    op.drop_table('assessments')
    op.drop_index('ix_appointments_student_scheduled', table_name='appointments')
    op.drop_index(op.f('ix_appointments_student_id'), table_name='appointments')
    op.drop_index('ix_appointments_status', table_name='appointments')
    op.drop_index(op.f('ix_appointments_scheduled_at'), table_name='appointments')
    op.drop_index('ix_appointments_counselor_scheduled', table_name='appointments')
    op.drop_index(op.f('ix_appointments_counselor_id'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_users_student_id_hash'), table_name='users')
    op.drop_index('ix_users_role_active', table_name='users')
    op.drop_index('ix_users_email_active', table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_campus_snapshots_university', table_name='campus_snapshots')
    op.drop_index(op.f('ix_campus_snapshots_snapshot_date'), table_name='campus_snapshots')
    op.drop_index('ix_campus_snapshots_date_period', table_name='campus_snapshots')
    op.drop_table('campus_snapshots')
    op.drop_index(op.f('ix_universities_slug'), table_name='universities')
    op.drop_index('ix_universities_active', table_name='universities')
    op.drop_table('universities')
    # ### end Alembic commands ###
