"""Core module exports."""
from app.core.security import (
    hash_password,
    verify_password,
    create_access_token,
    create_refresh_token,
    decode_token,
    verify_token_type,
    blacklist_token,
    is_token_blacklisted,
    encrypt_field,
    decrypt_field,
    hash_student_id,
    verify_student_id_hash,
    hash_ip,
    hash_user_agent,
)

from app.core.exceptions import (
    BeaconException,
    InvalidCredentialsError,
    TokenExpiredError,
    TokenInvalidError,
    TokenBlacklistedError,
    RefreshTokenRequiredError,
    ForbiddenError,
    InsufficientRoleError,
    NotFoundError,
    AlreadyExistsError,
    ValidationError,
    RateLimitError,
    CheckInLimitError,
    EscalationRequiredError,
    DataExportError,
    PrivacyThresholdError,
    InternalServerError,
    ServiceUnavailableError,
)

from app.core.permissions import (
    Role,
    Permission,
    ROLE_PERMISSIONS,
    get_permissions_for_role,
    role_has_permission,
    require_permission,
    require_role,
)

from app.core.privacy import (
    enforce_k_anonymity,
    add_privacy_metadata,
    mask_pii_in_logs,
    anonymize_student_data,
    apply_differential_privacy,
    suppress_small_groups,
    K_ANONYMITY_THRESHOLD,
)

__all__ = [
    # Security
    "hash_password",
    "verify_password",
    "create_access_token",
    "create_refresh_token",
    "decode_token",
    "verify_token_type",
    "blacklist_token",
    "is_token_blacklisted",
    "encrypt_field",
    "decrypt_field",
    "hash_student_id",
    "verify_student_id_hash",
    "hash_ip",
    "hash_user_agent",
    # Exceptions
    "BeaconException",
    "InvalidCredentialsError",
    "TokenExpiredError",
    "TokenInvalidError",
    "TokenBlacklistedError",
    "RefreshTokenRequiredError",
    "ForbiddenError",
    "InsufficientRoleError",
    "NotFoundError",
    "AlreadyExistsError",
    "ValidationError",
    "RateLimitError",
    "CheckInLimitError",
    "EscalationRequiredError",
    "DataExportError",
    "PrivacyThresholdError",
    "InternalServerError",
    "ServiceUnavailableError",
    # Permissions
    "Role",
    "Permission",
    "ROLE_PERMISSIONS",
    "get_permissions_for_role",
    "role_has_permission",
    "require_permission",
    "require_role",
    # Privacy
    "enforce_k_anonymity",
    "add_privacy_metadata",
    "mask_pii_in_logs",
    "anonymize_student_data",
    "apply_differential_privacy",
    "suppress_small_groups",
    "K_ANONYMITY_THRESHOLD",
]